name: Setup Go

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5.5.0
      id: setup-go
      with:
        go-version-file: "go.mod"
        cache-dependency-path: go.sum
    - name: Download go modules
      if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
      run: go mod download
      shell: bash
