name: Setup Go

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      id: setup-go
      with:
        go-version-file: "go.mod"
        cache-dependency-path: go.sum
    - name: Download go modules
      run: go mod download
      shell: bash
